# Generated by Django 4.0.6 on 2022-07-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0003_society_alter_about_id_alter_research_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='society',
        ),
    ]
