# Generated by Django 4.0.6 on 2022-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0005_research_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_drop',
            name='slug_drop',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
