# Generated by Django 4.0.6 on 2022-07-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0006_research_drop_slug_drop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_drop',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsidc_app.research'),
        ),
    ]
