# Generated by Django 4.0.6 on 2022-07-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0005_auto_20220719_0740'),
        ('nsidc_app', '0007_alter_research_drop_slug'),
    ]

    operations = [
    ]
