# Generated by Django 4.0.6 on 2022-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0013_alter_about_id_alter_informationresearch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_example_down_scientists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
