# Generated by Django 4.0.6 on 2022-07-28 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0018_archiveclass_myclass_alter_about_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveclass',
            name='releasedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='releasedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
