# Generated by Django 4.0.6 on 2022-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0020_alter_archiveclass_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveclass',
            name='releasedate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='releasedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
