# Generated by Django 4.0.6 on 2022-07-28 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0022_alter_archiveclass_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveclass',
            name='releasedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='releasedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
